---
name: 'Plan Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  standup-cluster:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ['ubuntu', '2404', 'amd64']
          - ['debian', '12', 'amd64']
          # debian 13 is not released yet, but we can get dailies...
          - ['debian', '13', 'amd64', 'daily-latest']
          - ['rocky', '9', 'x86_64']
    steps:
      - uses: actions/checkout@v4
      - id: local-action
        uses: ./ # Use kvm_automation_tooling's own standup-cluster action.yaml...
        with:
          os: ${{ matrix.os[0] }}
          os-version: ${{ matrix.os[1] }}
          os-arch: ${{ matrix.os[2] }}
          image_version: ${{ matrix.os[3] }}
          debug: true
          # Setting cpu_mode to host-model is necessary for redhat9
          # x86_64-v2 requirements (see README.md)
          vms: |-
            [
              {
                "role": "primary",
                "cpus": 2,
                "mem_mb": 4096,
                "cpu_mode": "host-model"
              },
              {
                "role": "agent",
                "cpu_mode": "host-model"
              }
            ]
      - name: Display inventory details
        working-directory: kvm_automation_tooling
        env:
          INVENTORY_JSON: ${{ steps.local-action.outputs.cluster-details }}
        run: |-
          jq . <<< $INVENTORY_JSON
      - name: Run teardown_cluster plan
        working-directory: kvm_automation_tooling
        run: |-
          bundle exec bolt plan run kvm_automation_tooling::teardown_cluster cluster_id="test"
