---
name: 'Plan Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  standup-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Terraform
        run: |-
          # From https://developer.hashicorp.com/terraform/install
          wget -O - https://apt.releases.hashicorp.com/gpg | \
            sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
      - name: Install Libvirt
        run: sudo apt-get install libvirt-daemon-system libvirt-dev
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install module dependencies
        run: bundle exec bolt module install
      - name: Write standup_cluster params
        run: |-
          cat > standup_cluster_params.json <<EOF
          {
            "cluster_name": "test",
            "network_addresses": "192.168.100.0/24",
            "ssh_public_key_path": "/some/path/to/ssh/id_for_vms.pub",
            "os": "ubuntu",
            "os_version": "2404",
            "os_arch": "x86_64",
            "architecture": "singular",
            "agents": 1,
          }
          EOF
      - name: Run standup_cluster plan
        run: bundle exec bolt plan run standup_cluster --params @standup_cluster_params.json
