---
name: 'Plan Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  standup-cluster:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ['ubuntu', '2404', 'amd64']
          - ['debian', '12', 'amd64']
    steps:
      - uses: actions/checkout@v4
      - id: local-action
        uses: ./ # Use kvm_automation_tooling's own standup-cluster action.yaml...
        with:
          os: ${{ matrix.os[0] }}
          os-version: ${{ matrix.os[1] }}
          os-arch: ${{ matrix.os[2] }}
          debug: true
          vms: |-
            [
              {
                "role": "primary",
                "cpus": 2,
                "mem_mb": 4096,
                "disk_gb": 5
              },
              {
                "role": "agent"
              }
            ]
      - name: Display inventory details
        working-directory: kvm_automation_tooling
        env:
          INVENTORY_JSON: ${{ steps.local-action.outputs.cluster-details }}
        run: |-
          jq . <<< $INVENTORY_JSON
      - name: Run teardown_cluster plan
        working-directory: kvm_automation_tooling
        env:
          PLATFORM: ${{ matrix.os[0] }}-${{ matrix.os[1] }}-${{ matrix.os[2] }}
        run: |-
          bundle exec bolt plan run kvm_automation_tooling::teardown_cluster cluster_id="test-singular-${PLATFORM}"
