---
name: 'PR Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rspec:
    strategy:
      matrix:
        ruby-version:
          - '3.2'
          - '3.3'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libvirt-dev library for ruby-libvirt gem
        run: sudo apt-get install libvirt-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install module dependencies
        run: bundle exec bolt module install
      - name: Symlink ruby_task_helper
        run: |-
          ln -s kvm_automation_tooling/.modules/ruby_task_helper ../ruby_task_helper
      - name: Run RSpec
        run: bundle exec rspec
