---
name: 'PR Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rspec:
    strategy:
      matrix:
        ruby-version:
          - '3.2'
          - '3.3'
# Not testing 3.4 yet; bundler fails here:
# bundler: failed to load command: bolt (/home/runner/work/kvm_automation_tooling/kvm_automation_tooling/vendor/bundle/ruby/3.4.0/bin/bolt)
# /home/runner/work/kvm_automation_tooling/kvm_automation_tooling/vendor/bundle/ruby/3.4.0/gems/puppet-8.10.0/lib/puppet/feature/base.rb:21:in '<top (required)>': Cannot determine basic system flavour (Puppet::Error)
#          - '3.4'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libvirt-dev library for ruby-libvirt gem
        run: sudo apt-get install libvirt-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install module dependencies
        run: bundle exec bolt module install
      - name: Symlink ruby_task_helper
        run: |-
          ln -s kvm_automation_tooling/.modules/ruby_task_helper ../ruby_task_helper
      - name: Run RSpec
        run: bundle exec rspec
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Run puppet-lint
        run: bundle exec puppet-lint manifests functions plans templates
